### ISSUE TITLE
Hosted on Azure

### ISSUE THREAD

**Issue by yboujraf** [ghrst/Kamailio-HA#6]
Dear @ghrst 

I 'd like to host two instances of Kamailio + RTPEngine on Azure and setup HA.

Do you have experience on that and is it workable ?

Best Regards,

**Comment by ghrst** [comment]
Dear @yboujraf 

If you want an active-passive setup (two Kamailio instances) you can use this repository. For an active-active scenario you need a different setup. Anyway both setups are possible...

**Comment by yboujraf** [comment]
Dear @ghrst 

i ´d like this setup : 
- A two node Active-Passive Kamailio Cluster with a cluster of RTPProxy servers

What about DB?

For operating system, we expected the latest Debian version. I see the script is supporting Debian 9.

Finally, are you providing services or consulting? We have a short description of what we expecting.

Best regards

**Comment by ghrst** [comment]
Dear @yboujraf 

- The setup that you want can be easily deployed using these scripts or by other means
- For database you can use MySQL, or other supported databases (it depends on your needs)
- I can provide you with both services and consulting. You can contact me using: reza_sabery_89@yahoo.com Email address

Regards
