### ISSUE TITLE
RTPEngine instead of RTProxy

### ISSUE THREAD

**Issue by yboujraf** [ghrst/Kamailio-HA#7]
Dear @ghrst 

As understood RTPEngine is replacing RTProxy.

Do you think to implement RTPEngine?

Bedt regards

**Comment by ghrst** [comment]
Dear @yboujraf 

Yes. RTPEngine is a better solution with more capabilities. I am going to replace RTPProxy with RTPEngine as soon as I find some time ... ;)

**Comment by yboujraf** [comment]
Dear @ghrst 

If you could update too kamailio v5.x will be great.

Best regards

**Comment by ghrst** [comment]
Dear @yboujraf

Great idea. Thx a lot.

**Comment by yboujraf** [comment]
Dear @ghrst 

If you need support for testing I will happy.

Best regards,

**Comment by ghrst** [comment]
Thx a lot dear @yboujraf
